### ISSUE TITLE
[BUG]: Button in Careers page is not aligned properly

### ISSUE THREAD

**Issue by vivekBoii** [SyedImtiyaz-1/PreciousServices-#95]
**Describe the bug**
Button in Careers page is not aligned properly

**To Reproduce**
1. Go to 'careers'
2. Scroll down to 'form'
3. See error

**Expected behavior**
should be aligned

**Screenshots**
https://drive.google.com/file/d/1T81onfx8hkMDpEQtjO48HQU9nKWMR-2T/view?usp=drive_link

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [ ] I have checked the existing issues
- [ ]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [ ] Have you added your name in [CONTRIBUTING.md](https://github.com/SyedImtiyaz-1/PreciousServices/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

**Can I solve this bug Under hacktoberfest**

**Comment by SyedImtiyaz-1** [comment]
Show me Screenshot.

**Comment by vivekBoii** [comment]
![Screenshot from 2023-10-01 15-13-55](https://github.com/SyedImtiyaz-1/PreciousServices-/assets/115945472/470e32e4-1889-4253-ba30-34ab035174b2)

**Comment by SyedImtiyaz-1** [comment]
Ok, got it actually its because of your screen ratio ok you can fix this error using CSS and make the button fix in the box. 
My Screen Ratio : 
![Screenshot from 2023-10-01 16-02-29](https://github.com/SyedImtiyaz-1/PreciousServices-/assets/121503426/b837f17c-3df4-425d-a03e-a0f7be55a0ad)


Your Screen Ratio  : 
![image](https://github.com/SyedImtiyaz-1/PreciousServices-/assets/121503426/fb431cd5-2932-43a8-a228-6e28bcf125a5)



If you can fix it then go for it I'm assigning it to you. 👍🏻

**Comment by Vivek7038** [comment]
hey i have sent a pull request here https://github.com/SyedImtiyaz-1/PreciousServices-/pull/103
which resolves this issue kindly check this

**Comment by SyedImtiyaz-1** [comment]
Great let me check @Vivek7038
